// Regenerates grade5-6.html and grade7-plus.html from index.html's 100 questions,
// using the TIER3/TIER4 id lists below as the source of truth for grade classification.
// Run with: node tools/split_tiers.js   (from anywhere; paths below are absolute)
// To move a question between tiers, edit the TIER3/TIER4 arrays and re-run.
// grade3-4.html and grades.html are hand-authored, not generated by this script.
const fs = require('fs');

const SRC = 'C:/Users/evolx/kids-math-puzzles/index.html';
const OUT_DIR = 'C:/Users/evolx/kids-math-puzzles';
const src = fs.readFileSync(SRC, 'utf8');

// ---- parse quests ----
const quests = {};
const questBlockRe = /(<div class="quest" data-q="([^"]+)">[\s\S]*?<\/div><\/div>)/g;
let m;
while ((m = questBlockRe.exec(src)) !== null) quests[m[2]] = m[1];

// ---- new AI-era pilot quests (World 7), hand-authored, not in original index.html ----
const CHK_SVG = '<svg viewBox="0 0 24 24" fill="none"><path d="M4 12l5 5L20 6" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const SPEAK_ROW = '<div class="speak-row"><button type="button" class="speak-btn" data-lang="en-US" aria-label="Read in English"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M3 9v6h4l5 5V4L7 9H3z"/><path d="M16.5 12c0-1.77-.77-3.29-2-4.24v8.48c1.23-.95 2-2.47 2-4.24z"/></svg>EN</button><button type="button" class="speak-btn" data-lang="zh-CN" aria-label="朗读中文"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M3 9v6h4l5 5V4L7 9H3z"/><path d="M16.5 12c0-1.77-.77-3.29-2-4.24v8.48c1.23-.95 2-2.47 2-4.24z"/></svg>中文</button></div>';
function makeQuest(id, lv, en, zh) {
  return `<div class="quest" data-q="${id}"><label class="chk"><input type="checkbox"><span class="box">${CHK_SVG}</span></label><span class="lv" data-lv="${lv}">Lv.${lv}</span><div>${SPEAK_ROW}<div class="en">${en}</div><div class="zh">${zh}</div><div class="answer-row"><input type="text" class="answer-input" placeholder="写下你的答案... / Your answer..."></div><div class="help-row"><button type="button" class="help-btn hint-btn">提示 Hint</button><button type="button" class="help-btn giveup-btn">认输看答案 Hands up</button></div><div class="hint-box" hidden></div><div class="answer-box" hidden></div></div></div>`;
}
quests['m7-01'] = makeQuest('m7-01', 3,
  "Xiaohua thinks of a number, adds 7, then multiplies the result by 2 — getting 26. What was the original number? An AI gave this solution: ‘Since 7×2=14, the number plus 14 equals 26, so the number is 12.’ Is the AI right? If not, where's the mistake, and what's the correct answer?",
  "小华心里想一个数，把它加7以后，再乘以2，结果是26。小华想的是几？AI给出的解法是：\"因为7乘以2等于14，所以这个数加14等于26，这个数就是12。\"AI对吗？如果不对，错在哪，正确答案是多少？");
quests['m7-02'] = makeQuest('m7-02', 3,
  "Rule: If it rains, the ground gets wet. You see the ground is wet. An AI concludes: ‘So it must have rained.’ Is the AI's conclusion definitely correct? Why or why not?",
  "已知规则：如果下雨，地面就会湿。现在看到地面是湿的。AI说：\"所以一定是下雨了。\"AI的结论一定对吗？为什么？");
quests['m7-03'] = makeQuest('m7-03', 3,
  "Xiaoming is 3 years older than Xiaohong. How old is Xiaoming this year? Can this be solved? If not, what information is missing?",
  "小明比小红大3岁。请问小明今年多少岁？这道题能解出来吗？如果不能，还缺什么信息？");

// ---- world display names (zh, en) ----
const WORLD_META = {
  m1: ['称重与信息推理', 'Weighing &amp; Information Logic'],
  m2: ['组合与计数思维', 'Combinatorics &amp; Counting'],
  m3: ['逻辑推演谜题', 'Deductive Logic Puzzles'],
  m4: ['空间与几何思维', 'Spatial &amp; Geometric Thinking'],
  m5: ['数字游戏与数论', 'Number Games &amp; Number Theory'],
  m6: ['策略博弈与决策', 'Game Strategy &amp; Optimal Decisions'],
  m7: ['AI时代思维', 'AI-Era Thinking'],
};
const WORLD_BADGE = { m1: '01', m2: '02', m3: '03', m4: '04', m5: '05', m6: '06', m7: '07' };

// grade5-6.html — realistic grade-5/6 difficulty
const TIER3 = ['m1-01','m1-02','m1-03','m1-04','m1-05','m1-06','m1-07','m1-08','m1-09','m1-16',
  'm2-01','m2-02','m2-03','m2-06','m2-07','m2-08','m2-09','m2-10','m2-12',
  'm3-01','m3-02','m3-03','m3-04','m3-05','m3-06','m3-07','m3-08','m3-09','m3-11','m3-12',
  'm4-01','m4-02','m4-03','m4-05','m4-06','m4-08','m4-10','m4-13','m4-15',
  'm5-01','m5-02','m5-03','m5-04','m5-06','m5-07','m5-08','m5-09','m5-10','m5-16',
  'm6-01','m6-02','m6-03','m6-06','m6-08','m6-13','m6-15','m6-17',
  'm7-01','m7-02','m7-03'];

// grade7-plus.html — genuinely 7th-grade+/challenge difficulty (kept, not deleted, per 2026-07-27 decision)
const TIER4 = ['m1-10','m1-11','m1-12','m1-13','m1-14','m1-15','m1-17',
  'm2-04','m2-05','m2-11','m2-13','m2-14','m2-15','m2-16',
  'm3-10','m3-13','m3-14','m3-15','m3-16','m3-17',
  'm4-04','m4-07','m4-09','m4-11','m4-12','m4-14','m4-16','m4-17',
  'm5-05','m5-11','m5-12','m5-13','m5-14','m5-15',
  'm6-04','m6-05','m6-07','m6-09','m6-10','m6-11','m6-12','m6-14','m6-16'];

function groupByWorld(ids) {
  const byWorld = {};
  ids.forEach(id => {
    const w = id.split('-')[0];
    (byWorld[w] = byWorld[w] || []).push(id);
  });
  const order = Object.keys(quests);
  Object.keys(byWorld).forEach(w => byWorld[w].sort((a, b) => order.indexOf(a) - order.indexOf(b)));
  return byWorld;
}

function renderWorldSection(w, ids) {
  const [zh, en] = WORLD_META[w];
  const count = ids.length;
  const questsHtml = ids.map(id => quests[id]).join('\n    ');
  return `<section class="world" id="${w}">
  <div class="world-head">
    <span class="badge">WORLD ${WORLD_BADGE[w]}</span>
    <h2>${zh}</h2>
    <span class="en">${en}</span>
    <span class="count">${count} 题</span>
  </div>
  <div class="quests">
    ${questsHtml}
  </div>
</section>`;
}

function renderNavCard(w, ids) {
  const [zh, en] = WORLD_META[w];
  const count = ids.length;
  return `  <a href="#${w}"><span class="num">WORLD ${WORLD_BADGE[w]} · ${count}题</span><span class="name">${zh}</span><span class="en">${en}</span>
    <span class="prog"><span class="track"><i data-prog="${w}"></i></span><span data-count="${w}">0/${count}</span></span></a>`;
}

function renderHudIcon(w, zh) {
  return `      <a href="#${w}" title="${zh}" style="--card-c:var(--w${w.slice(1)})">${WORLD_BADGE[w]}</a>`;
}

function buildPage(opts) {
  const { file, tierPrefix, title, metaDesc, kicker, h1, h1Accent, subZh, subEn, byWorld, footerNote } = opts;
  const worldOrder = Object.keys(byWorld).sort((a, b) => a.localeCompare(b));
  const total = worldOrder.reduce((s, w) => s + byWorld[w].length, 0);
  const worldIdsJs = '[' + worldOrder.map(w => `'${w}'`).join(',') + ']';
  const totalsJs = '{' + worldOrder.map(w => `${w}:${byWorld[w].length}`).join(',') + '}';

  const hudIcons = worldOrder.map(w => renderHudIcon(w, WORLD_META[w][0])).join('\n');
  const navCards = worldOrder.map(w => renderNavCard(w, byWorld[w])).join('\n');
  const worldSections = worldOrder.map(w => renderWorldSection(w, byWorld[w])).join('\n\n');

  const html = `<!doctype html>
<html lang="zh">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<meta name="description" content="${metaDesc}">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='22' fill='%23E8792C'/%3E%3Cpath d='M30 38a12 12 0 0 1 12-12h4a8 8 0 0 0 8 8 8 8 0 0 0 8-8h4a12 12 0 0 1 12 12v4a8 8 0 0 0-8 8 8 8 0 0 0 8 8v4a12 12 0 0 1-12 12h-4a8 8 0 0 0-8-8 8 8 0 0 0-8 8h-4a12 12 0 0 1-12-12v-4a8 8 0 0 0 8-8 8 8 0 0 0-8-8z' fill='%23FFF8EC'/%3E%3C/svg%3E">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@500;700;800&family=Nunito:ital,wght@0,400;0,600;0,800;1,600&family=JetBrains+Mono:wght@500;700&family=Noto+Sans+SC:wght@400;600;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="shared.css">
</head>
<body>

<div class="hud">
  <div class="wrap hud-inner">
    <div class="hud-score">已闯关 <b id="hudCount">0</b> / ${total}</div>
    <div class="hud-bar"><i id="hudFill"></i></div>
    <div class="hud-worlds">
${hudIcons}
    </div>
    <button class="theme-btn" id="themeBtn" aria-label="切换深浅色模式">◐</button>
  </div>
</div>

<div class="wrap">

<header class="hero">
  <p class="kicker"><span class="dot"></span>${kicker}</p>
  <h1>${h1}<span class="accent">${h1Accent}</span></h1>
  <p class="sub">${subZh}
    <span class="en">${subEn}</span>
  </p>
</header>

<nav class="map">
${navCards}
</nav>

${worldSections}

<footer>
  <span>${footerNote}</span>
  <div style="display:flex; gap:10px; flex-wrap:wrap;">
    <button id="reportBtn" style="font-family:'Nunito',sans-serif; font-weight:800; color:#fff; background:var(--brand); border:none; border-radius:999px; padding:7px 16px; cursor:pointer; font-size:13px;">生成做题报告 · Report for parents</button>
    <button id="parentBtn" style="font-family:'Nunito',sans-serif; font-weight:800; color:#fff; background:var(--good); border:none; border-radius:999px; padding:7px 16px; cursor:pointer; font-size:13px;">家长中心 · Parent Center</button>
    <button id="resetBtn">重置打卡进度 · Reset progress</button>
  </div>
</footer>

</div>

<div class="report-overlay" id="reportOverlay">
  <div class="report-card">
    <div class="report-head">
      <h2>做题报告 · Progress Report</h2>
      <button class="report-close" id="reportClose" aria-label="关闭">✕</button>
    </div>
    <p class="report-sub">把下面的内容复制发给家长，让他们知道做了哪些题、写了什么答案。<br>Copy this and send it to a parent so they can see what's been done.</p>
    <div class="report-actions">
      <button id="reportCopyBtn">复制报告 · Copy report</button>
      <button id="reportDownloadBtn" class="secondary">下载文件 · Download .txt</button>
    </div>
    <div class="report-body" id="reportBody"></div>
    <p class="report-copy-note" id="reportCopyNote"></p>
  </div>
</div>

<div class="report-overlay" id="parentOverlay">
  <div class="report-card">
    <div class="report-head">
      <h2>家长中心 · Parent Center</h2>
      <button class="report-close" id="parentClose" aria-label="关闭">✕</button>
    </div>
    <p class="report-sub">每日做题统计，以及逐题核对孩子的答案并标记对错（用于计算正确率）。<br>Daily progress stats, plus grade each answer against the reference solution to track accuracy.</p>
    <div class="report-body" id="parentBody"></div>
  </div>
</div>

<script>window.TIER_PREFIX = '${tierPrefix}'; window.WORLD_IDS = ${worldIdsJs}; window.WORLD_TOTALS = ${totalsJs};</script>
<script src="shared.js"></script>
</body>
</html>
`;
  fs.writeFileSync(OUT_DIR + '/' + file, html, 'utf8');
  console.log('wrote', file, '-', total, 'questions across', worldOrder.length, 'worlds:', worldOrder.map(w => w + '(' + byWorld[w].length + ')').join(' '));
}

const byWorld3 = groupByWorld(TIER3);
const byWorld4 = groupByWorld(TIER4);

buildPage({
  file: 'grade5-6.html',
  tierPrefix: 'g56',
  title: '思维闯关 · 五六年级 · 奥数基础题库',
  metaDesc: '面向五六年级的奥数思维训练题，六大板块，中英对照，配图示，家长中心可查看每日进度。',
  kicker: 'Grade 5-6 · Foundation Level',
  h1: '思维闯关',
  h1Accent: '五六年级',
  subZh: '五六年级适龄的经典奥数题型，六个板块由浅入深，帮孩子把思维练扎实，为以后的竞赛打基础。',
  subEn: 'Grade 5-6 level classic olympiad-style puzzles across six themed worlds — building the thinking skills that competition math rewards.',
  byWorld: byWorld3,
  footerNote: `共 ${TIER3.length} 题 · 五六年级基础题库`,
});

buildPage({
  file: 'grade7-plus.html',
  tierPrefix: 'g7p',
  title: '思维闯关 · 七年级+挑战题库',
  metaDesc: '面向七年级及以上、想挑战更难题目的孩子，包含多道经典世界级难题，中英对照。',
  kicker: 'Grade 7+ · Challenge Level',
  h1: '思维闯关',
  h1Accent: '七年级+挑战',
  subZh: '难度更高的经典题型，包括几道公认的世界级难题（比如史上最难逻辑题）。这些不是任何年级的"必做题"，是给学有余力、想挑战自己的孩子准备的加餐。',
  subEn: 'Harder classics for grade 7+, including a few world-famous "hardest ever" puzzles. These are optional stretch challenges, not grade-level requirements.',
  byWorld: byWorld4,
  footerNote: `共 ${TIER4.length} 题 · 七年级以上挑战题库`,
});
